version: '3.8'

services:
  mongodb:
    image: mongo:8
    container_name: product-catalog-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: product_catalog_oms
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local

