# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://<db_username>:<db_password>@democluster.elz1q.mongodb.net/?retryWrites=true&w=majority&appName=Demo-PC-OMS
spring.data.mongodb.database=demo_pc_oms

# Server Configuration
server.port=8080

# Application Name
spring.application.name=demo_pc_oms

# Logging
logging.level.org.springframework.data.mongodb=DEBUG

# Jackson JSON Configuration
# Exclude null fields from JSON responses for cleaner API output
spring.jackson.default-property-inclusion=non_null

